# see https://help.sonatype.com/en/config-yaml.html

# external DB PostgreSQL connection
database:
  type: postgresql
  hostname: ${DATABASE_HOSTNAME}
  port: ${DATABASE_PORT}
  name: ${DATABASE_NAME}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}

# Directory for data files.
sonatypeWork: /sonatype-work

# Path to a license file to automatically install if unlicensed.
licenseFile: /sonatype-license.lic

# Base URL of the Sonatype CLM server for user facing links back to the server.
# If a mail server is configured, then the baseUrl setting must also be enabled and correct as otherwise notification emails cannot be sent.
# baseUrl: ${BASE_URL}
# We inject baseUrl via JAVA_OPTS

# Hour of the day(0-23) to schedule Policy Monitoring execution. The default is midnight.
#policyMonitoringHour: 0

# Enables/disables cross-site request forgery protection. Defaults to true for increased security.
csrfProtection: false

# A custom fragment to add to the "user-agent" for HTTP calls
#userAgentSuffix: "example fragment"

# HTTP-specific options.
server:
  # The context path for the application. Note that this must have a leading slash.
  applicationContextPath: /

  applicationConnectors:
    - type: http

      # The port on which the HTTP server listens for service requests.
      # Because Java cannot drop privileges in a POSIX system, these
      # ports cannot be in the range 1-1024. A port value of 0 will
      # make the OS use an arbitrary unused port.
      port: 8070

      # The hostname of the interface to which the application HTTP server socket
      # will be bound. If omitted, the socket will listen on all
      # interfaces.
      #bindHost: 127.0.0.1  # only bind to loopback

  adminConnectors:
    - type: http

      # The port on which the HTTP server listens for administrative
      # requests. Subject to the same limitations as "port".
      port: 8071

      # The hostname of the interface to which the admin HTTP server socket
      # will be bound. If omitted, the socket will listen on all
      # interfaces.
      #bindHost: 127.0.0.1  # only bind to loopback

  # HTTP request log settings.
  requestLog:
    appenders:
      # Settings for logging to a file.
      - type: file

        # The file to which current statements will be logged.
        currentLogFilename: /var/log/nexus-iq-server/request.log

        logFormat: '%clientHost %l %user [%date] "%requestURL" %statusCode %bytesSent %elapsedTime "%header{User-Agent}"'

        # When the log file rotates, the archived log will be renamed to this and gzipped. The
        # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
        # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
        archivedLogFilenamePattern: /var/log/nexus-iq-server/request-%d.log.gz

        # The number of archived files to keep.
        archivedFileCount: 5

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: DEBUG

  # Logger-specific settings.
  loggers:
    "com.sonatype.insight.scan": INFO
    "eu.medsea.mimeutil.MimeUtil2": INFO
    "org.apache.http": INFO
    "org.apache.http.wire": ERROR
    "org.eclipse.birt.report.engine.layout.pdf.font.FontConfigReader": WARN
    "org.eclipse.jetty": INFO
    "org.apache.shiro.web.filter.authc.BasicHttpAuthenticationFilter": INFO # WARNING: This reveals credentials at DEBUG level
    "org.quartz": INFO
    "com.networknt.schema": OFF
    "com.sonatype.insight.audit":
      appenders:
        - type: file
          # The file to which audit statements will be logged.
          currentLogFilename: /var/log/nexus-iq-server/audit.log
          # When the audit log file rotates, the archived audit log will be renamed to this and gzipped. The
          # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
          # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
          #
          # If archive is true, this must be specified.
          archivedLogFilenamePattern: /var/log/nexus-iq-server/audit-%d.log.gz
          # The number of archived audit log files to keep.
          archivedFileCount: 5
    "com.sonatype.insight.policy.violation":
      appenders:
        - type: file
          # The file to which policy violations will be logged.
          currentLogFilename: /var/log/nexus-iq-server/policy-violation.log
          # When the policy violation log file rotates, the archived policy violation log will be renamed to this
          # and gzipped. The %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
          # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
          #
          # If archive is true, this must be specified.
          archivedLogFilenamePattern: /var/log/nexus-iq-server/policy-violation-%d.log.gz
          # The number of archived policy violation log files to keep.
          archivedFileCount: 5

  appenders:
    # Settings for logging to stdout.
    - type: console

      # Do not display log statements below this threshold to stdout.
      threshold: INFO

      logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"

      # Settings for logging to a file.
    - type: file

      # Do not write log statements below this threshold to the file.
      threshold: ALL

      logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"

      # The file to which current statements will be logged.
      currentLogFilename: /var/log/nexus-iq-server/clm-server.log

      # When the log file rotates, the archived log will be renamed to this and gzipped. The
      # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
      # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
      #
      # If archive is true, this must be specified.
      archivedLogFilenamePattern: /var/log/nexus-iq-server/clm-server-%d.log.gz

      # The number of archived files to keep.
      archivedFileCount: 5

# Sample data is created for new installs.
#createSampleData: true
